"""Integration between predict module and existing closed loops.

Connects predictors to autonomous loops for preventive action:
- DriftPredictor → DriftAutoCorrect (preventive retraining)
- AnomalyDetector → LatencyAutoScale (cost spike response)
- HealthScore → corrective alerts
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable

from aegis.predict.anomaly import AnomalyDetector, AnomalyDirection
from aegis.predict.drift import DriftPredictor, DriftSeverity
from aegis.predict.health_score import HealthScore, HealthStatus


class AlertType(str, Enum):
    DRIFT_PREDICTED = "drift_predicted"
    COST_SPIKE = "cost_spike"
    HEALTH_CRITICAL = "health_critical"
    HEALTH_WARNING = "health_warning"
    LATENCY_SPIKE = "latency_spike"


@dataclass(frozen=True)
class PredictiveAlert:
    """An alert generated by the prediction-loop integration."""

    alert_type: AlertType
    agent_id: str
    message: str
    severity: str
    details: dict[str, Any]
    timestamp: float
    action_taken: str = ""  # what the system did in response


# Callback types
AlertCallback = Callable[[PredictiveAlert], None]
ActionCallback = Callable[[PredictiveAlert], dict[str, Any]]


class PredictiveLoopIntegration:
    """Bridges predictors with autonomous loops for preventive action.

    Usage::

        integration = PredictiveLoopIntegration(
            drift_predictor=pred,
            anomaly_detector=detector,
            health_score=hs,
        )
        integration.on_alert(my_callback)  # register alert handler
        integration.on_drift_action(my_retrain_fn)  # preventive action

        # Evaluate current state and trigger actions
        alerts = integration.evaluate("agent-1", current_metrics)

    Parameters
    ----------
    drift_predictor : DriftPredictor
        For predicting faithfulness/quality drift.
    anomaly_detector : AnomalyDetector
        For detecting anomalous metric values.
    health_score : HealthScore
        For computing agent health.
    drift_action_threshold : DriftSeverity
        Minimum severity to trigger preventive drift correction.
    health_action_threshold : float
        Health score below which corrective action triggers.
    """

    def __init__(
        self,
        *,
        drift_predictor: DriftPredictor | None = None,
        anomaly_detector: AnomalyDetector | None = None,
        health_score: HealthScore | None = None,
        drift_action_threshold: DriftSeverity = DriftSeverity.MEDIUM,
        health_action_threshold: float = 60.0,
    ) -> None:
        self._drift = drift_predictor or DriftPredictor()
        self._anomaly = anomaly_detector or AnomalyDetector()
        self._health = health_score or HealthScore()
        self._drift_threshold = drift_action_threshold
        self._health_threshold = health_action_threshold

        self._alert_callbacks: list[AlertCallback] = []
        self._drift_action: ActionCallback | None = None
        self._cost_action: ActionCallback | None = None
        self._health_action: ActionCallback | None = None
        self._alerts_history: list[PredictiveAlert] = []

    @property
    def alerts_history(self) -> list[PredictiveAlert]:
        return list(self._alerts_history)

    def on_alert(self, callback: AlertCallback) -> None:
        """Register a callback for all alerts."""
        self._alert_callbacks.append(callback)

    def on_drift_action(self, callback: ActionCallback) -> None:
        """Register action when drift is predicted (e.g., trigger DriftAutoCorrect)."""
        self._drift_action = callback

    def on_cost_action(self, callback: ActionCallback) -> None:
        """Register action when cost spike detected (e.g., trigger LatencyAutoScale)."""
        self._cost_action = callback

    def on_health_action(self, callback: ActionCallback) -> None:
        """Register action when health drops below threshold."""
        self._health_action = callback

    def evaluate(
        self,
        agent_id: str,
        metrics: dict[str, float],
        *,
        drift_metric: str = "faithfulness",
        drift_horizon: float = 48.0,
    ) -> list[PredictiveAlert]:
        """Evaluate current state and generate alerts / trigger actions.

        Parameters
        ----------
        agent_id : str
            The agent to evaluate.
        metrics : dict
            Current metric values (latency_p95, error_rate, cost_per_day, etc.).
        drift_metric : str
            Metric to check for drift prediction.
        drift_horizon : float
            Hours ahead to predict.

        Returns
        -------
        list[PredictiveAlert]
            Alerts generated during this evaluation.
        """
        now = time.time()
        alerts: list[PredictiveAlert] = []

        # 1. Check drift prediction
        drift_pred = self._drift.predict(drift_metric, horizon_hours=drift_horizon)
        severity_order = [
            DriftSeverity.OK, DriftSeverity.LOW,
            DriftSeverity.MEDIUM, DriftSeverity.HIGH, DriftSeverity.CRITICAL,
        ]
        if (
            drift_pred.severity != DriftSeverity.OK
            and severity_order.index(drift_pred.severity)
            >= severity_order.index(self._drift_threshold)
        ):
            alert = PredictiveAlert(
                alert_type=AlertType.DRIFT_PREDICTED,
                agent_id=agent_id,
                message=drift_pred.message,
                severity=drift_pred.severity.value,
                details={
                    "metric": drift_pred.metric,
                    "current": drift_pred.current_value,
                    "predicted": drift_pred.predicted_value,
                    "time_to_threshold": drift_pred.time_to_threshold_hours,
                },
                timestamp=now,
                action_taken=self._run_action(self._drift_action, alert_type=AlertType.DRIFT_PREDICTED, agent_id=agent_id, message=drift_pred.message, severity=drift_pred.severity.value, details={"metric": drift_pred.metric}, timestamp=now),
            )
            alerts.append(alert)

        # 2. Check for cost anomaly
        cost_val = metrics.get("cost_per_day")
        if cost_val is not None:
            anomaly = self._anomaly.check("cost", cost_val)
            if anomaly.is_anomaly and anomaly.direction == AnomalyDirection.SPIKE:
                alert = PredictiveAlert(
                    alert_type=AlertType.COST_SPIKE,
                    agent_id=agent_id,
                    message=f"Cost spike detected: ${cost_val:.2f} (score={anomaly.score:.1f})",
                    severity="high" if anomaly.score > 4.0 else "medium",
                    details={"value": cost_val, "anomaly_score": anomaly.score},
                    timestamp=now,
                    action_taken=self._run_action(self._cost_action, alert_type=AlertType.COST_SPIKE, agent_id=agent_id, message=f"Cost spike: ${cost_val:.2f}", severity="high", details={"value": cost_val}, timestamp=now),
                )
                alerts.append(alert)

        # 3. Check for latency anomaly
        lat_val = metrics.get("latency_p95")
        if lat_val is not None:
            anomaly = self._anomaly.check("latency", lat_val)
            if anomaly.is_anomaly and anomaly.direction == AnomalyDirection.SPIKE:
                alert = PredictiveAlert(
                    alert_type=AlertType.LATENCY_SPIKE,
                    agent_id=agent_id,
                    message=f"Latency spike: {lat_val:.0f}ms (score={anomaly.score:.1f})",
                    severity="high" if anomaly.score > 4.0 else "medium",
                    details={"value": lat_val, "anomaly_score": anomaly.score},
                    timestamp=now,
                )
                alerts.append(alert)

        # 4. Check health score
        snap = self._health.compute(agent_id, metrics)
        if snap.status == HealthStatus.CRITICAL:
            alert = PredictiveAlert(
                alert_type=AlertType.HEALTH_CRITICAL,
                agent_id=agent_id,
                message=f"Health critical: {snap.score:.0f}/100",
                severity="critical",
                details={"score": snap.score, "components": snap.components},
                timestamp=now,
                action_taken=self._run_action(self._health_action, alert_type=AlertType.HEALTH_CRITICAL, agent_id=agent_id, message=f"Health: {snap.score:.0f}", severity="critical", details={"score": snap.score}, timestamp=now),
            )
            alerts.append(alert)
        elif snap.status == HealthStatus.WARNING:
            alert = PredictiveAlert(
                alert_type=AlertType.HEALTH_WARNING,
                agent_id=agent_id,
                message=f"Health warning: {snap.score:.0f}/100",
                severity="warning",
                details={"score": snap.score, "components": snap.components},
                timestamp=now,
            )
            alerts.append(alert)

        # Notify all callbacks
        for a in alerts:
            self._alerts_history.append(a)
            for cb in self._alert_callbacks:
                cb(a)

        return alerts

    def _run_action(self, callback: ActionCallback | None, **kwargs: Any) -> str:
        """Run an action callback if registered. Returns action description."""
        if callback is None:
            return ""
        try:
            # Build a minimal alert for the callback
            alert = PredictiveAlert(**kwargs)
            result = callback(alert)
            return str(result) if result else "action_executed"
        except Exception as exc:
            return f"action_failed: {exc}"
